import {
  AgentFeedAbortError,
  AgentFeedApiError,
  AgentFeedError,
  AgentFeedResponseError,
  AgentFeedTimeoutError,
  AgentFeedTransportError,
  type AgentFeedErrorOptions,
} from "./errors.ts";
import {
  defaultSleep,
  resolveRetryPolicy,
  retryDelayMilliseconds,
  type RetryPolicy,
  type RetryPolicyOverrides,
  type RetrySleepOptions,
} from "./retry.ts";
import {
  FetchTransport,
  isAbortLike,
  isTimeoutLike,
  type AgentFeedHttpMethod,
  type AgentFeedTransport,
  type AgentFeedTransportResponse,
} from "./transport.ts";

export interface AgentFeedClientOptions {
  readonly base_url?: string;
  readonly baseUrl?: string;
  /** Bearer token. It is never included in errors or diagnostics. */
  readonly token?: string;
  readonly transport?: AgentFeedTransport;
  readonly headers?: Readonly<Record<string, string>>;
  /** Per-attempt timeout; omitted means 30 seconds. */
  readonly timeout_ms?: number;
  readonly timeoutMs?: number;
  readonly retry?: RetryPolicyOverrides;
  /** Injectable for deterministic tests and non-browser runtimes. */
  readonly sleep?: RetrySleepOptions["sleep"];
  readonly random?: RetrySleepOptions["random"];
}

export interface AgentFeedRequestOptions {
  readonly signal?: AbortSignal;
  /** Override the client's per-attempt timeout for this operation. */
  readonly timeout_ms?: number;
  readonly timeoutMs?: number;
  readonly retry?: RetryPolicyOverrides;
}

interface RequestSpec {
  readonly operation: string;
  readonly method: AgentFeedHttpMethod;
  readonly path: string;
  readonly body?: unknown;
  readonly expected_status?: ReadonlySet<number>;
  /** GET is intrinsically idempotent; mutations are safe only with a key. */
  readonly idempotent?: boolean;
  /** Set only for endpoints whose contract defines idempotency-key semantics. */
  readonly idempotency_keyed?: boolean;
}

interface AttemptSignal {
  readonly signal: AbortSignal;
  readonly timed_out: () => boolean;
  readonly dispose: () => void;
}

const DEFAULT_TIMEOUT_MS = 30_000;
const TRANSIENT_STATUSES = new Set([408, 425, 429, 500, 502, 503, 504]);
const SAFE_IDEMPOTENCY_KEY = /^[^\s]{1,512}$/u;

function object(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function safeApiCode(value: unknown): string | null {
  if (typeof value !== "string" || !/^[a-z0-9][a-z0-9_.-]{0,99}$/u.test(value)) return null;
  return value;
}

function headerValue(headers: Readonly<Record<string, string>> | undefined, name: string): string | null {
  if (!headers || typeof headers !== "object") return null;
  const wanted = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === wanted && typeof value === "string") return value;
  }
  return null;
}

function boundedRequestId(headers: Readonly<Record<string, string>> | undefined): string | null {
  const value = headerValue(headers, "x-request-id") ?? headerValue(headers, "x-correlation-id");
  // Only accept formats generated by common tracing systems. Arbitrary
  // server headers are untrusted and may echo a credential or source data.
  return value !== null && (
    /^[0-9a-f]{32,64}$/iu.test(value)
    || /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu.test(value)
  ) ? value : null;
}

function retryAfterSeconds(headers: Readonly<Record<string, string>> | undefined): number | null {
  const value = headerValue(headers, "retry-after");
  if (value === null) return null;
  const seconds = Number(value);
  return Number.isFinite(seconds) && seconds >= 0 && seconds <= 86_400 ? seconds : null;
}

function timeoutValue(value: number | undefined): number {
  const result = value ?? DEFAULT_TIMEOUT_MS;
  if (!Number.isSafeInteger(result) || result < 1) throw new Error("invalid_timeout_ms");
  return result;
}

function mergeUrl(base: URL, path: string): URL {
  // `base` always has a trailing slash in AgentFeedClient. Relative joining
  // preserves an optional deployment prefix such as https://host/agent-feed/.
  return new URL(path.replace(/^\//u, ""), base);
}

function hasIdempotencyKey(value: unknown): boolean {
  const record = object(value);
  if (!record) return false;
  const candidate = record.idempotency_key ?? record.idempotencyKey;
  return typeof candidate === "string" && SAFE_IDEMPOTENCY_KEY.test(candidate);
}

function bodyString(value: unknown): string | undefined {
  if (value === undefined) return undefined;
  const serialized = JSON.stringify(value);
  if (serialized === undefined) throw new Error("request_body_not_serializable");
  return serialized;
}

function decodedBody(response: AgentFeedTransportResponse): unknown {
  const body = response.body;
  if (body === undefined || typeof body === "object" && body !== null && !(body instanceof Uint8Array)) return body;
  if (body instanceof Uint8Array) {
    const text = new TextDecoder().decode(body);
    if (text.length === 0) return undefined;
    try { return JSON.parse(text) as unknown; } catch { return text; }
  }
  if (typeof body === "string") {
    if (body.length === 0) return undefined;
    try { return JSON.parse(body) as unknown; } catch { return body; }
  }
  return body;
}

function createAttemptSignal(parent: AbortSignal | undefined, timeoutMs: number): AttemptSignal {
  const controller = new AbortController();
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    controller.abort("agent-feed-timeout");
  }, timeoutMs);
  const onAbort = (): void => {
    if (!controller.signal.aborted) controller.abort(parent?.reason);
  };
  if (parent?.aborted) onAbort();
  else parent?.addEventListener("abort", onAbort, { once: true });
  return {
    signal: controller.signal,
    timed_out: () => timedOut,
    dispose: () => {
      clearTimeout(timer);
      parent?.removeEventListener("abort", onAbort);
    },
  };
}

function abortError(operation: string): AgentFeedAbortError {
  return new AgentFeedAbortError({ operation });
}

function timeoutError(operation: string): AgentFeedTimeoutError {
  return new AgentFeedTimeoutError({ operation });
}

function safeTransportError(operation: string): AgentFeedTransportError {
  return new AgentFeedTransportError({ operation, retryable: true });
}

function responseError(operation: string, status: number | null = null): AgentFeedResponseError {
  return new AgentFeedResponseError({ operation, status });
}

/** Shared request engine used by producer and consumer clients. */
export abstract class AgentFeedClient {
  readonly #baseUrl: URL;
  readonly #transport: AgentFeedTransport;
  readonly #headers: Readonly<Record<string, string>>;
  readonly #token: string | undefined;
  readonly #timeoutMs: number;
  readonly #retry: RetryPolicy;
  readonly #sleep: (milliseconds: number, signal: AbortSignal) => Promise<void>;
  readonly #random: () => number;

  protected constructor(options: AgentFeedClientOptions) {
    const baseUrl = options.base_url ?? options.baseUrl;
    if (typeof baseUrl !== "string" || baseUrl.length === 0) throw new Error("base_url_required");
    let base: URL;
    try {
      base = new URL(baseUrl);
    } catch {
      throw new Error("base_url_invalid");
    }
    if (base.protocol !== "http:" && base.protocol !== "https:") throw new Error("base_url_scheme_invalid");
    if (base.username !== "" || base.password !== "") throw new Error("base_url_credentials_not_allowed");
    if (base.search !== "" || base.hash !== "") throw new Error("base_url_query_or_fragment_not_allowed");
    base.pathname = `${base.pathname.replace(/\/+$/u, "")}/`;
    this.#baseUrl = base;
    this.#transport = options.transport ?? new FetchTransport();
    this.#headers = Object.freeze({ ...(options.headers ?? {}) });
    this.#token = options.token;
    if (this.#token !== undefined && (this.#token.length === 0 || /[\r\n]/u.test(this.#token))) throw new Error("token_invalid");
    this.#timeoutMs = timeoutValue(options.timeout_ms ?? options.timeoutMs);
    this.#retry = resolveRetryPolicy(options.retry);
    this.#sleep = options.sleep ?? defaultSleep;
    this.#random = options.random ?? Math.random;
  }

  protected async requestJson<T>(spec: RequestSpec, options: AgentFeedRequestOptions = {}): Promise<T> {
    const requestBody = bodyString(spec.body);
    const retryableRequest = spec.idempotent === true
      || (spec.idempotency_keyed === true && hasIdempotencyKey(spec.body));
    const retry = resolveRetryPolicy({ ...this.#retry, ...(options.retry ?? {}) });
    const timeoutMs = timeoutValue(options.timeout_ms ?? options.timeoutMs ?? this.#timeoutMs);
    let lastRetryAfter: number | null = null;

    for (let attempt = 1; attempt <= retry.max_attempts; attempt += 1) {
      if (options.signal?.aborted) throw abortError(spec.operation);
      const attemptSignal = createAttemptSignal(options.signal, timeoutMs);
      let response: AgentFeedTransportResponse;
      try {
        const url = mergeUrl(this.#baseUrl, spec.path);
        const headers: Record<string, string> = {
          accept: "application/json",
          ...this.#headers,
          ...(requestBody === undefined ? {} : { "content-type": "application/json" }),
          ...(this.#token === undefined ? {} : { authorization: `Bearer ${this.#token}` }),
        };
        response = await this.#transport.request({
          method: spec.method,
          url: url.toString(),
          headers,
          ...(requestBody === undefined ? {} : { body: requestBody }),
          signal: attemptSignal.signal,
        });
      } catch (error) {
        attemptSignal.dispose();
        if (options.signal?.aborted) throw abortError(spec.operation);
        if (attemptSignal.timed_out() || isTimeoutLike(error)) {
          if (retryableRequest && attempt < retry.max_attempts) {
            await this.#wait(spec.operation, retry, attempt, null, options.signal);
            continue;
          }
          throw timeoutError(spec.operation);
        }
        if (isAbortLike(error)) throw abortError(spec.operation);
        if (error instanceof AgentFeedError) {
          if (retryableRequest && error.retryable && attempt < retry.max_attempts) {
            await this.#wait(spec.operation, retry, attempt, error.retry_after_seconds, options.signal);
            continue;
          }
          throw error;
        }
        if (retryableRequest && attempt < retry.max_attempts) {
          await this.#wait(spec.operation, retry, attempt, null, options.signal);
          continue;
        }
        throw safeTransportError(spec.operation);
      }
      const timedOut = attemptSignal.timed_out();
      attemptSignal.dispose();
      // A custom transport may ignore AbortSignal and resolve late. Enforce
      // the timeout at the client boundary instead of accepting that response.
      if (options.signal?.aborted) throw abortError(spec.operation);
      if (timedOut) {
        if (retryableRequest && attempt < retry.max_attempts) {
          await this.#wait(spec.operation, retry, attempt, null, options.signal);
          continue;
        }
        throw timeoutError(spec.operation);
      }

      if (response === null || typeof response !== "object" || !Number.isSafeInteger(response.status)) {
        throw responseError(spec.operation);
      }

      const retryAfter = retryAfterSeconds(response.headers);
      lastRetryAfter = retryAfter;
      if (response.status >= 200 && response.status < 300) {
        if (spec.expected_status !== undefined && !spec.expected_status.has(response.status)) {
          throw responseError(spec.operation, response.status);
        }
        return decodedBody(response) as T;
      }

      const body = object(decodedBody(response));
      const apiCode = safeApiCode(body?.error);
      const requestId = boundedRequestId(response.headers);
      const retryableResponse = retryableRequest && TRANSIENT_STATUSES.has(response.status);
      if (retryableResponse && attempt < retry.max_attempts) {
        await this.#wait(spec.operation, retry, attempt, retryAfter, options.signal);
        continue;
      }
      if (apiCode !== null) {
        throw new AgentFeedApiError(apiCode, {
          operation: spec.operation,
          status: response.status,
          retryable: retryableResponse,
          request_id: requestId,
          retry_after_seconds: retryAfter,
        });
      }
      throw new AgentFeedError("api_error", "agent_feed_http_error", {
        operation: spec.operation,
        status: response.status,
        retryable: retryableResponse,
        request_id: requestId,
        retry_after_seconds: retryAfter,
      });
    }
    // The loop always returns or throws. This guard protects future changes
    // while keeping a stable redacted error if the policy is altered.
    throw new AgentFeedError("api_error", "agent_feed_http_error", {
      operation: spec.operation,
      retryable: false,
      retry_after_seconds: lastRetryAfter,
    });
  }

  async #wait(
    operation: string,
    policy: RetryPolicy,
    retryNumber: number,
    retryAfter: number | null,
    signal: AbortSignal | undefined,
  ): Promise<void> {
    const delay = retryDelayMilliseconds(policy, retryNumber, retryAfter, this.#random);
    const controller = new AbortController();
    const onAbort = (): void => controller.abort(signal?.reason);
    if (signal?.aborted) throw abortError(operation);
    signal?.addEventListener("abort", onAbort, { once: true });
    try {
      await this.#sleep(delay, controller.signal);
    } catch (error) {
      if (signal?.aborted || error instanceof AgentFeedAbortError) throw abortError(operation);
      throw safeTransportError(operation);
    } finally {
      signal?.removeEventListener("abort", onAbort);
    }
  }
}

export type { AgentFeedErrorOptions };
